# Model parameters file
model: 'convSpeechModelE'
params:
    melspec_shape: [122, 64]
    mfcc_shape: [122, 20]
    sf_size: 122
    window: 512
    num_mel_bins: 64
    num_mfccs: 20
    batch_size: 128
    silence_size: 4
    num_iterations: 10000
    min_loss: 0.1
    display_step: 10
    checkpoint_step: 500
    learning_rate: 5.0e-04
    dropout_prob_value: 0.50
    noise_factor_value: 0.1
    noise_frac_value: 0.25
    unknown_weight: 0.075
    unknown_weight_scaler: 0.0
